# Generated by Django 6.0.4 on 2026-05-05 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dosis', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateField()),
                ('frecuencia_horas', models.IntegerField()),
                ('proxima_toma', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
