# Generated by Django 6.0.4 on 2026-05-07 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_medicamento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='principal.tratamiento'),
        ),
    ]
