# Generated by Django 6.0.4 on 2026-05-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fcm_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token de Firebase'),
        ),
    ]
