# Generated by Django 6.0.4 on 2026-05-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_perfil_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='notif_final_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='notif_previa_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='notif_toma_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
