# Generated by Django 6.0.4 on 2026-05-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_medicamento_notif_final_enviada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='razon',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de posponer'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='notif_3min_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
