# Generated by Django 6.0.4 on 2026-05-10 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_historial_razon_medicamento_notif_3min_enviada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={},
        ),
        migrations.CreateModel(
            name='RegistroSueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_dormir', models.DateTimeField(blank=True, null=True)),
                ('hora_despertar', models.DateTimeField(blank=True, null=True)),
                ('horas_dormidas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('minutos_extra', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
