# Generated by Django 6.0.4 on 2026-05-14 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_perfil_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='familiar_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familiares_bajo_supervision', to=settings.AUTH_USER_MODEL, verbose_name='Familiar Supervisor'),
        ),
    ]
