# Generated by Django 6.0.4 on 2026-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_perfil_familiar_a_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
